config/routes.rb
Rails.application.routes.draw do
  match '/404' => 'errors#error404', via: [:get, :post, :patch, :delete]

  get '/sitemap' => 'sitemap#index'
  get '/news' => 'static_pages#news'
  get '/about' => 'static_pages#about'

  root 'posts#index'

  resources :posts
  devise_for :users

end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  include AlgoliaSearch
  algoliasearch do
    attribute :title, :contact, :content, :category, :id, :created_at, :slug
  end

  friendly_id :title, use: :slugged

  POST_TYPES = ['Jobs', 'Cars for Sale', 'Properties for Sale', 'Rent or Share', 'Things for Sale', 'Something Else'].freeze
  validates :title, :contact, :content, presence: true
  validates :title, length: { maximum: 40 }
  before_save :fix_title, :replace_frags

  mount_uploader :postpic, PostpicUploader

  protected

  def fix_title
    self.title = title.titleize
  end

  def replace_frags
    self.content = content.gsub(/\/i+/, ' ')
    self.title = title.gsub(/\/i+/, ' ')

    self.content = content.gsub(/&amp;Amp;/, '&')
    self.title = title.gsub(/&Amp;/, '&')
  end

  

  end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :null_session, if: proc { |c| c.request.format == 'application/json' }
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def error404
    render status: :not_found
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]



  # GET /posts
  # GET /posts.json
  def index
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    # @similar_posts = @post.similar_posts
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
        format.html {     
          if verify_recaptcha(model: @post) && @post.save
            redirect_to @post, notice: 'Post was successfully created.' 
          else
            render :new
          end
          }
        format.json { 
          if @post.save
            render :show, status: :created, location: @post
          else
            render json: @post.errors, status: :unprocessable_entity
          end 
        }
     
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if verify_recaptcha(model: @post) && @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private



  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:category, :postpic, :contact, :content, :title, :tag_list)
  end
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  def index
    @host = "#{request.protocol}#{request.host}"
    @posts = Post.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def news
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sitemap_helper.rb
module SitemapHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
    <%- if content_for? :page_title -%>
    <%= yield :page_title %> .. Mate Na Lavo Fiji Classifieds
    <% else %>
    Mate Na Lavo Free Fiji Classifieds
    <% end %>
    </title>
    <meta charset="UTF-8">
    <meta name="description" content="Fiji's biggest free classifieds. Whether you're in Suva, Nadi, Lautoka or Savusavu, we help you find a new car, a job, or a new house today! ">
    <%= csrf_meta_tags %>
    <meta name="keywords" content="Fiji, Viti Levu, Vanua Levu, free, classifieds, vacancy, for sale, jobs, houses, land, cars, autos" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <p id="notice"><%= notice %></p>
    <%= yield %>
    <div class="pt3" style="clear:both" >
      <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      <!-- matenalavo -->
      <ins class="adsbygoogle"
      style="display:block"
      data-ad-client="ca-pub-8870945451217756"
      data-ad-slot="2469094028"
      data-ad-format="auto"></ins>
      <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
      </script>
    </div>
  </body>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-66625922-1', 'auto');
  ga('send', 'pageview');
  </script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tachyons/4.6.2/tachyons.min.css">
  <footer class="tc-l bg-center cover">
    <div class="w-100 ph3 pv3 bg-black-60">
      <p class='center'>Mate Na Lavo is Fiji's largest free classifieds service. We help Fijians find jobs, cars, houses and more.</p>
      <a class="link white-60 bg-transparent hover-white inline-flex items-center ma2 tc br2 pa2" href="." title="Home">
        <?xml version="1.0" encoding="iso-8859-1"?>
        <!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
        <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="35px" viewBox="0 0 611.997 611.998"
          xml:space="preserve">
          <g>
            <g>
              <path d="M511.114,300.251c-9.94,0-17.638,7.663-17.638,17.651v241.105H368.401v-98.453c0-9.236-7.697-17.31-17.002-17.31h-90.435
                c-9.948,0-17.96,8.073-17.96,17.31v98.453h-124.76v-233.1c0-9.306-7.69-17.036-17.638-17.036c-9.298,0-16.995,7.73-16.995,17.036
                v250.752c0,9.305,7.697,17.036,16.995,17.036h160.358c9.298,0,16.995-7.731,16.995-17.036v-98.454h55.801v98.454
                c0,9.305,7.697,17.036,17.639,17.036h159.715c9.299,0,16.995-7.731,16.995-17.036V317.903
                C528.109,307.915,520.413,300.251,511.114,300.251z"/>
                <path d="M607.003,314.003L467.819,174.225V78.919c0-9.921-8.019-17.583-17.96-17.583c-9.305,0-17.001,7.663-17.001,17.583v60.345
                  L318.046,23.774c-3.518-3.558-7.697-5.474-11.864-5.474c-4.81,0-8.983,1.984-12.507,5.474L5.361,312.087
                  c-6.917,6.91-7.375,17.994,0,24.357c6.411,7.389,17.454,6.91,24.371,0l276.45-275.793l275.807,278.393
                  c2.873,2.874,7.054,4.516,12.507,4.516c4.81,0,8.976-1.642,12.507-4.516C613.42,332.613,613.899,320.982,607.003,314.003z"/>
            </svg>
            <span class="f6 ml3 pr2">Home</span>
          </a>
          <a class="link white-60 bg-transparent hover-white inline-flex items-center ma2 tc br2 pa2" href="https://www.facebook.com/matenalavo/" title="Facebook/Matenalavo">
            <svg class="dib h2 w2" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414"><path d="M15.117 0H.883C.395 0 0 .395 0 .883v14.234c0 .488.395.883.883.883h7.663V9.804H6.46V7.39h2.086V5.607c0-2.066 1.262-3.19 3.106-3.19.883 0 1.642.064 1.863.094v2.16h-1.28c-1 0-1.195.476-1.195 1.176v1.54h2.39l-.31 2.416h-2.08V16h4.077c.488 0 .883-.395.883-.883V.883C16 .395 15.605 0 15.117 0" fill-rule="nonzero"/></svg>
            <span class="f6 ml3 pr2">Facebook</span>
          </a>
          <a class="link white-60 bg-transparent hover-white inline-flex items-center ma2 tc br2 pa2" href="/about" title="About">
            <?xml version="1.0" encoding="iso-8859-1"?>
            <!-- Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
            <svg class="dib h2 w2" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" height="px"
              viewBox="0 0 455 455" xml:space="preserve">
              <path d="M227.5,0C101.855,0,0,101.855,0,227.5c0,47.551,14.598,91.688,39.544,128.193L9.662,445.338l89.646-29.881
                C135.812,440.403,179.949,455,227.5,455C353.145,455,455,353.145,455,227.5C455,101.855,353.145,0,227.5,0z"/>
              </svg>
              <span class="f6 ml3 pr2">What's MateNaLavo?</span>
            </a>
          </html>

app/views/posts/_form.html.erb
<script src="//cdn.ckeditor.com/4.5.8/standard/ckeditor.js"></script>

<%= form_for @post, html:{class:'form-horizontal'} do |f| %>
<% if @post.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
  <ul>
    <% @post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title,  style: 'width: 100%', :placeholder => "Headline for your ad"  %>
</div>
<div class="field">
  <%= f.label :contact %><br>
  <%= f.text_field :contact, style: 'width: 100%', :placeholder => "Phone and/or email address"  %>
</div>
<div class="field">
  <%= f.label :category %><br>
  <%= f.select :category, Post::POST_TYPES,{},:class =>"form-control", style: 'width: 100%'  %>
</div>
<div class="field">
  <%= f.label :content %><br>
  <%= f.text_area :content ,style: 'width: 100%', rows:10, :placeholder => "Your main content goes here. Please include details such as your location(Suva,Nadi,Lautoka,SavuSavu etc. You can upload pictures to flickr,imgur,photobucket etc and then use the picture tool to put the image in your ad.)"%>
  <script>
     CKEDITOR.replace( 'post[content]' );
  </script>
</div>
<hr><h5>Upload a picture</h5>
<%= f.file_field :postpic %>
<hr>
<%= recaptcha_tags %>

<div class="actions" align="center">
  <%= f.submit "Post my Ad", class: "btn btn-large btn-primary"%>
</div>




<% end %>

app/views/posts/_list.html.erb
<%# app/views/students/_list.html.erb %>
<div class='Grid' align='center'>
	<div class="list-group">
		<% posts.each do |post| %>
		<a href="<%= post_path(post) %>" class="list-group-item Grid-H <%= post.category.partition(" ").first %>">
			<h3 class="list-group-item-heading" style="display:inline-block;flex:3;" > <%= post.title %></h3>
			<span class="list-group-item-text Grid-cell"><%= post.category %> <%= time_ago_in_words(post.created_at)%> ago<% if user_signed_in? %>
				<%= link_to "Delete", post_path(post), method: :delete, class:"btn" %>
			<% end %></span>
		</a>
		
		<%end%>
	</div>
</div>
<div id="paginator">
	<%= paginate @posts, :remote => true %>
</div>

app/views/posts/edit.html.erb
<div class="mw5 mw6-ns center">

<h1>Editing Post</h1>

<%= render 'form' %>


</div>

app/views/posts/index.html.erb
<!doctype html>
<html>
  <head>
    <title>Mate Na Lavo</title>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <!-- IE < 10 support -->
    <!--[if lte IE 9]>
    <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/instantsearch.js/1/instantsearch.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
  </head>
  <body>
    <!-- INTERFACE -->
    <header>
      <a href="." title="Home"><%= image_tag 'matenalavo.com.png',size:"170x50", alt: "matenalavo.com"%></a>
      <div id="search-input"></div>
    </header>
    <main>
    <div id="left-column">
          <div class="pa3">
          <%= link_to 'Post a free Ad', new_post_path, class: "f6 grow no-underline br-pill ph3 pv2 mb2 dib white bg-black" %>
      </div>
      <div id="category" class="facet"></div>
    </div>
    <div id="right-column">
      <div id="stats"></div>
      <div id="hits"></div>
    </div>
    <div id="pagination"></div>

    </main>
    <!-- /INTERFACE -->
    <!-- TEMPLATES -->
    <script type="text/html" id="hit-template">
    <div class="hit">
      <div class="hit-content">
        <article class="center mw5 mw6-ns hidden ba mv2">
          <h1 class="f4 bg-near-black white mv0 pv2 ph3 hit-name">{{{_highlightResult.title.value}}}<a class="fr" href="posts/{{slug}}">link</a></h1>
          <div class="pa3 bt">
            <p class="f6 f5-ns lh-copy measure mv0 hit-description">
              {{{_snippetResult.content.value}}}
            </p>
            <h4 id="posting_time"><i>Posted at {{created_at}}</i></h4>
          </div>
        </article>
        
      </div>
    </div>
    </script>
    <script type="text/html" id="no-results-template">
    <div id="no-results-message">
      <p>We didn't find any results for the search <em>"{{query}}"</em>.</p>
      <a href="." class='clear-all'>Clear search</a>
    </div>
    </script>
    <!-- /TEMPLATES -->
    <!-- SCRIPTS -->
    <script src="//cdn.jsdelivr.net/instantsearch.js/1/instantsearch.min.js"></script>
    <%= javascript_include_tag "app.js"%>
    <!-- /SCRIPTS -->
  </body>
</html>

app/views/posts/new.html.erb
<div class="mw5 mw6-ns center">

<h1>Posting an Ad</h1>

<%= render 'form' %>


</div>

app/views/posts/show.html.erb
<% content_for :page_title do
@post.title
end %>
<% cache @post do %>


<article class="center mw5 mw6-ns hidden ba mv4">
  <h1 class="f4 bg-near-black white mv0 pv2 ph3"><%= @post.title %></h1>
  <div class="pa3 bt">
    <p class="f6 f5-ns lh-copy measure mv0">
      
    <p>
      <strong>Contact Info:</strong>
      <%= @post.contact %>
    </p>
    <p><i>Posted at <%= (@post.created_at+12*60*60).strftime('%H:%M %a %d %b %Y') %></i></p>
    <hr>
    <p>
      <%= @post.content.html_safe %>
    </p>
    <% unless @post.postpic_url.nil? %>
    <hr><h4>Attached Image</h4>
    <%= image_tag @post.postpic_url(:standard) %><br /><% end %>
    <br>
    
    <!-- Buttons end here -->
    <p>
      <strong>Category:</strong>
      <%= @post.category %>
    </p>
    </p>
  </div>
</article>

    <div align="center">
      <%= link_to 'Back', posts_path, class: "btn btn-block btn-default" %><br>
    </div>

  <% end %>

app/views/sitemap/index.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc><%= @host %></loc>
   </url>
   <url>
      <loc><%= "#{@host}#{about_path}" %></loc>
   </url>
   <url>
      <loc><%= "#{@host}#{posts_path}" %></loc>
   </url>
   <% @posts.each do |post| %>
     <url>
        <loc><%= "#{@host}/posts/#{post.friendly_id}" %></loc>
     </url>
   <% end %>
</urlset>

app/views/static_pages/about.html.erb
<div class="mw5 mw6-ns center">

<h1>About Mate Na Lavo!</h1>
<br>
<p><h4><i><strong>Mate Na Lavo</strong></i> is a Fijian saying that literally translates to "the money is dead".</h4> The meaning is that the speaker has made such a good deal that they don't need to think about the money anymore and the matter has been laid to rest. </p>

<p>We think Fiji deserves a great classifieds service is open for everyone to use. We aim to make <strong>Mate Na Lavo</strong> the most comprehensive and easy to use classifieds board in Fiji. Whether you're looking for a job, a used car or a new home, <strong>Mate Na Lavo</strong> wants to be your number one choice! Let us know how we can improve, email <a href="mailto:tevitadromodromo@gmail.com">Tevita</a>

</div>

app/views/static_pages/news.html.erb
<div class="mw5 mw6-ns center">

<h1>News and Developments</h1>
<h3>Upgrades<h3>
<h3>1-03-2016</h3>
<p>Since over 50% of our visitors are accessing the site using a mobile device, we've been hard at work to 1. Reduce page load times 2. Increase mobile friendliness of the user interface. Stay tuned! </p>
<h3>1-01-2016</h3>
<p>Happy new year! Lots more improvements coming soon!</p>
<h3>16-08-2015 We are in development!</h3>
<p>We are currently in development! Please let us know if you find any errors/bugs or have suggestions on how we can improve! You can email <a href="mailto:tevitadromodromo@gmail.com">Tevita</a></p>



</div>